google/aarch64-paging

src/paging.rs
The length specified in the format string includes the "0x" at the start, so it should be two more than the number of digits we want. Implementing `Debug` is useful for being able to derive it on other types which contain a `VirtualAddress` or `PhysicalAddress`.
=> Fix width of formatted addresses, and add Debug implementation

src/paging.rs
`RootTable::new` should panic if someone attempts to create a pagetable with an invalid root level.
=> Check that root level is valid, and add helper functions and constants

src/idmap.rs, src/lib.rs, src/paging.rs
Return an error if the caller tries to map virtual addresses which are outside the range supported by the page table given its root level.
=> Add bounds check to map_range.

src/paging.rs
Adds addition and subtraction for `VirtualAddress` and `PhysicalAddress`, and conversion from `Range<VirtualAddress>` to `MemoryRegion` (with the same alignment logic as `MemoryRegion::new`).
=> Implement useful traits for address types and `MemoryRegion`

src/idmap.rs, src/lib.rs, src/linearmap.rs, src/paging.rs
This required some refactoring because the methods on the `Translation` trait need to take `self` to know the offset, and so the `Translation` needs to be passed around to the various methods which access the page table. I've achieved this by adding it as a field on the `PageTableWithLevel`.
To avoid duplicating code I've moved the common methods from `IdMap` out to a new shared struct called `Mapping`, which takes the `Translation` on construction. `Translation` is then implemented by `IdTranslation` and `LinearTranslation`, and `IdMap` becomes an alias for `Mapping<IdTranslation>`.
Suggestions are welcome on better names.
=> Add support for linear mapping

.github/workflows/rust.yml, CHANGELOG.md, Cargo.toml, src/idmap.rs, src/lib.rs, src/linearmap.rs, src/paging.rs
This PR makes the `Translation` trait responsible for allocating page tables. This should help make it possible to use more complex mapping schemes, and to construct page tables in a different context to where they are used. This also allows allows us to make the `alloc` dependency optional (as it's only used by `IdMap` and `LinearMap`, not the core pagetable code).
TODO:
=> Prepare for more complex mapping schemes

src/linearmap.rs, src/paging.rs
`LinearMap` and any other mapping which may have different alignment of virtual and physical addresses was incorrectly using block mappings in cases where the physical address didn't have the required alignment. The architecture requires that we only make block mappings when the physical addresses are aligned to the size of the block, so this fixes the code to do that, and adds a test.
=> Fix bug with block mappings for non-identity map page tables

CHANGELOG.md, src/idmap.rs, src/lib.rs, src/linearmap.rs, src/paging.rs
=> Support TTBR1 as well as TTBR0

src/paging.rs
Rather than keeping a copy in each `PageTableWithLevel` we can just keep it in the `RootTable` and pass a reference around when needed.
This is an alternative to #18.
=> Avoid cloning Translation.

src/idmap.rs, src/lib.rs, src/linearmap.rs, src/paging.rs
Adds `modify_range`, a new API method that allows modification of page table entries corresponding to a virtual address range. The method receives a virtual address range, and an updater function. It is applied to every individual page table entry in virtual address range.
Also, this change exposes software flags and DBM (dirty state management) flag from `paging::Attributes`, as well as additional API on `paging::Descriptor` which allows modifying descriptor flags.
=> Allow modifying a range of page table entries

src/paging.rs
Use `self` rather than `&self` on `Descriptor` methods as it is `Copy`, and merge the two `MemoryRegion` implementation blocks.
=> Minor cleanups

CHANGELOG.md, Cargo.toml, src/paging.rs
This is a breaking change because it changes the API of `Attributes` which is part of the public API.
=> Update to latest version of bitflags.

CHANGELOG.md, src/idmap.rs, src/lib.rs, src/linearmap.rs, src/paging.rs
Break up invalid block entries into a new subtable when a new range smaller than the block is mapped. Also, allow mapping block and page entries without a VALID bit.
=> Allow mapping invalid leaf entries

src/idmap.rs, src/lib.rs, src/linearmap.rs, src/paging.rs
Unlike modify_range(), this uses a bound on the type F defining the prototype of the callback function. This is necessary because walking the page tables using an immutable reference to the Mapping object requires a mutable closure, and this cannot be achieved using a dynamic function type like PteUpdater.
=> Implement walk_range for traversing page tables

CHANGELOG.md, src/idmap.rs, src/lib.rs, src/linearmap.rs
They change memory mappings, so the caller must ensure that the program is still able to run correctly with the new mappings.
=> Mark activate and deactivate methods as unsafe.

CHANGELOG.md, src/idmap.rs, src/linearmap.rs, src/paging.rs
Drop the PteUpdater dynamic function type which is no longer used. Preserve some of its documentation, by merging it into the documentation for modify_range and walk_range. While at it, synchronize the documentation of the different implementations in idmap.rs, linearmap.rs and paging.rs
=> Remove PteUpdater function type and consolidate documentation around it

src/idmap.rs, src/linearmap.rs, src/paging.rs
walk_range() does not widen the range argument to the callback function, so stop claiming this is the case in the doc comments
=> Fix inaccurate documentation

CHANGELOG.md, src/idmap.rs, src/lib.rs, src/linearmap.rs
This is useful for applications which need to set TTBRn_ELx directly for some reason, such as those running in EL2 or EL3.
=> Add methods to get physical address of root table

src/paging.rs
These weren't updated when allocation was moved to the `Translation` trait.
=> Fix safety comments for PageTableWithLevel::free.

CHANGELOG.md, Cargo.toml, README.md, src/idmap.rs, src/lib.rs, src/linearmap.rs, src/paging.rs
This adds a parameter to the constructors to specify which exception level the page table is intended for, and then uses it in `activate` and `deactivate` to choose the appropriate TTBR.
=> Add support for EL2 and EL3 page tables

CHANGELOG.md, src/idmap.rs, src/lib.rs, src/linearmap.rs, src/paging.rs
This adds some attribute bits relevant to other translation regimes. I've also removed the assumption that MAIR registers are programmed a particular way. It should be up to the user of the library to decide how they want to use the different memory attributes, so this library can just provide flags for the attribute indices and the user can define their own constants based on that.
=> Add more attribute bits

CHANGELOG.md, src/idmap.rs, src/lib.rs, src/linearmap.rs, src/paging.rs
Users may want to have hardware manage the access flag, or implement software handling on fault, so let them choose whether to set it.
=> Don't automatically set ACCESSED flag on all mappings.

CHANGELOG.md, src/idmap.rs, src/lib.rs, src/linearmap.rs, src/paging.rs
This should make it easier for users of the library to keep state in their `Translation` implementation if they want to.
=> Don't require Translation to be Clone, and pass `&mut self` to allocation methods

CHANGELOG.md, src/paging.rs
There's no reason for them not to be, a shared reference to them is safe to use from any thread.
=> Make PageTableWithLevel (and types containing it) Sync.

src/idmap.rs, src/lib.rs, src/linearmap.rs, src/paging.rs
Also changed safety comments to a consistent style. There is no functional change.
=> Deny unsafe_op_in_unsafe_fn.

CHANGELOG.md, Cargo.toml, src/lib.rs, src/linearmap.rs, src/paging.rs, src/target.rs
This can be used as part of the build process for some firmware to embed a static pagetable in the binary image.
=> Add Translation for pregenerating a static pagetable for some target

CHANGELOG.md, src/lib.rs, src/mair.rs
These let a constant MAIR value be built with a builder pattern and named constants, which should be more readable and safer than using bitwise operations directly. Display implementations are also included to format MAIR values in a human-readable form.
=> Add types to build MAIR values.

CHANGELOG.md, src/paging.rs
Also added `EMPTY` associated constant to `Descriptor` and `PageTable` for use in const contexts.
=> Implement Default for various types

CHANGELOG.md, src/paging.rs
Needed this for a project, thought I'd see if anyone else wanted it upstreamed.
=> Make `output_address` method on `Descriptor` public

README.md
ARMv9 introduces support for 128-bit page table descriptors, which completely changes how the page table hierarchy is constructed. This is not trivial to support, and therefore not attempted for the time being.
=> Document that only 64-bit page table descriptors are supported

CHANGELOG.md, src/idmap.rs, src/lib.rs, src/linearmap.rs, src/paging.rs
This fixes #67.
Also added some more bits to `Attributes`.
=> Return Attributes from Descriptor::flags even if there are unknown bits

Cargo.lock, Cargo.toml, src/lib.rs, src/paging.rs, src/target.rs
Even though we model them as arbitrary arrays of usize in memory, live page tables are actually referenced by the page table walker, which is a separate observer in ARM ARM parlance.
So instead, treat it as an array of AtomicUsize, so that we obtain the following properties:
- no Copy or Clone traits, and so all manipulations of descriptors are guaranteed to operate on the descriptor directly, using atomic accesses
- all stores are issued with release semantics, which guarantees that th page table walker cannot observe stores in the wrong order (e.g., a table entry being updated before the table in question has been fully populated)
The Descriptor type does implement clone(), for where it is needed explicitly (there is a single case where a descriptor is copied into a variable to perform …
=> Deal with memory ordering in page tables

src/paging.rs
This is required to require BTI for indirect forward-edge jumps landing on the page.
=> Add support for GP bit
